Ice cream reducer
larkinds/recurse-randomice pull request #69
Opened 2023-10-02 15:44 UTC by pearlescence-m

Solves #51

2023-10-02 15:54 UTC, larkinds requested changes
This looks great, and it works! Good work. Just one small change - the example of the working reducer is in App.tsx

2023-10-02 15:54 UTC, larkinds commented on client/src/App.tsx
Reminder to keep App clean! Perhaps move this to some sort of example file?

2023-10-02 16:07 UTC, pearlescence-m commented on client/src/App.tsx
Cleaned the app.tsx!

2023-10-03 15:35 UTC, larkinds approved these changes
Sweet, thanks!

2023-10-03 15:36 UTC, merged