useLocalStorage + useReducer + useContext
larkinds/recurse-randomice pull request #81
Opened 2023-10-10 13:20 UTC by pearlescence-m

In this PR I refactored and merged all the code we had on these three topics. The working version can be applied to Cart, Checkout, Single Product page and Hall of Fame. The resulting local storage hooks are used in 2 contexts: user and cart, but they are reusable could be potentially applied to the new contexts.

- For #44, this solution can remove items from cart through reducer. 
  - [ ]  Need to add the part to clear localStorage entirely (probably one more useEffect in useLocalStorage hook)
- For #54, this solution works for all of the cart action types: incrementing, decrementing, adding, removing items.
  - [ ] Need to apply actions to buttons in Cart
- For #53, this solution works for all of the action types on the single product page: increasing and decreasing quantity. On Hall of Fame page, local storage seems to persist items.
  - [ ] Need to apply actions on the single product page

I might look into the remaining action items once the pending on Checkout/Cart refactor, Hall of Fame and Home Page PRs are merged.

2023-10-23 18:00 UTC, larkinds requested changes
Great work with this refactor and the detailed documentation! 

Just a few items to be addressed, and a few items for clean up.

2023-10-23 18:00 UTC, larkinds commented on client/src/Components/ProductCard.tsx
> +          {/* Need to write code to search ice-cream by id from localStorage below */}
this looks like it may be handled in the map statement - is this something for clean up?

2023-10-23 18:00 UTC, larkinds commented on client/src/Components/ProductCard.tsx
> +            <strong>description</strong>: <span>{props.description}</span>
this span is probably not needed, since it doesn't have separate styling or functionality

2023-10-23 18:00 UTC, larkinds commented on client/src/reducers/cartReducer.tsx
> +const changeQuantity = (
this needs some sort of guard against having a negative amount of icecream

2023-10-23 18:00 UTC, larkinds commented on client/src/reducers/cartReducer.tsx
> +    case "ADD_ICECREAM": {
this needs a way to guard against the same icecream being added twice as separate items in the iceCream array

2023-10-23 18:00 UTC, larkinds commented on client/src/reducers/cartReducer.tsx
> +const changeTopping = (
make sure that the # of toppings can't below 0 here please!

2023-10-23 18:00 UTC, larkinds commented on client/src/reducers/cartReducer.tsx
> +const changeQuantity = (
In addition, when an iceCream hits an amount of 0 it should probably be removed!

2023-10-25 15:46 UTC, pearlescence-m commented on client/src/reducers/cartReducer.tsx
> +const changeQuantity = (
Good catch, thanks! Implemented these things in the new commits

2023-10-25 15:46 UTC, pearlescence-m commented on client/src/reducers/cartReducer.tsx
> +    case "ADD_ICECREAM": {
Good point, pushed new code!

2023-11-06 19:43 UTC, eyeriss42 approved these changes

2023-11-06 19:47 UTC, pearlescence-m commented
@larkinds hi! I fixed all the requested changes and wanted to ask if you have any other comments. Otherwise, we might need this to be approved and merged for the next issues.

2023-11-21 18:43 UTC, larkinds approved these changes
Looks good! Great work :)

2023-11-22 16:54 UTC, merged